X0 = 10.0  # Initial number of preys
Y0 = 10.0  # Initial number of predators
ALPHA = 0.1  # Maximum prey per capita growth rate
BETA = 0.02  # Effect of the presence of predators on the prey growth rate
DELTA = 0.02  # Effect of the presence of prey on the predator's growth rate
GAMMA = 0.4  # Predator's per capita death rate
DT = 0.1  # Time step interval
T_FINAL = 1000  # Time of the simulation
METHOD = "rk4"  # Lotka Volterra variation method
SAVE_PATH = ""
